
#define the base image
FROM python:3.7



# creating a working directory
WORKDIR /app

# copy all the requieremnts into the new directory created
COPY requirements.txt ./requirements.txt
#install all that is in the requirements.txt

RUN pip install -r requirements.txt

#expose the port to be used to run the application
EXPOSE 8501
# Copy our app from the current directory to the working area
COPY . /app


#Create an entry point to make our image executable

ENTRYPOINT [ "streamlit", "run" ]
CMD ["app.py"]




